"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 2, 2]
linemode = "none"
show_hidden = false
show_symlink = true
sort_by = "mtime"
sort_dir_first = true
sort_reverse = true
sort_sensitive = true

[preview]
tab_size = 2
max_width = 4000
max_height = 4000
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]
