fork = true
frame = "full"
idle = true
no-multigrid = false
theme = "auto"
neovim-bin = "/usr/bin/nvim"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["JetBrainsMono Nerd Font", "Noto Color Emoji"]
size = 15
