#!/bin/sh
set -eu

out=$(niri msg focused-window)

col=$(printf '%s\n' "$out" | grep -Po 'Scrolling position:\s*column\s*\K[0-9]+')

if [ "$col" = "1" ]; then
  niri msg action maximize-column
else
  niri msg action maximize-column
  sleep 0.05
  niri msg action focus-column-left
  niri msg action focus-column-right
fi
