#!/bin/bash
msg="$*"
target_class="zen-browser"

nirius focus -a chrome-chatgpt.com__-Default

sleep 0.1

if [[ -z "$msg" ]]; then
  msg="$(cliphist list | cliphist decode | wl-copy >/dev/null && wl-paste)"
fi

wtype -M alt 1 -m alt
sleep 0.05
wtype i
wtype -k backspace

sleep 0.05

printf '%s' "$msg" | wl-copy
sleep 0.05
wtype -M ctrl v -m ctrl
